[package]
name = "sus_compiler"
version = "0.0.1"
authors = ["VonTum <lennart.vanhirtum@gmail.com>"]
edition = "2021"
repository = "https://github.com/pc2/sus-compiler"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7" # for terminal colors
# chumsky = "0.9.2"
ariadne = "0.3.0" # for nice errors

#lsp
lsp-server = {version = "0.7.1", optional = true}
lsp-types = {version = "0.94.0", optional = true}
serde_json = {version = "1.0.97", optional = true}
serde = {version = "1.0.156", optional = true}
#tower-lsp = {version = "0.19.0", optional = true}
#tokio = { version = "1.28.2", features = ["full"], optional = true }

[features]
lsp = ["lsp-server", "lsp-types", "serde_json", "serde"]

