name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      # Don't try to build codegen, as it needs to link against LLVM
      run: cargo build --verbose --features lsp
    - name: Run tests
      run: cargo test --verbose --features lsp

  # check-fmt:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: recursive
  #   - name: cargo fmt --check
  #     run: cargo fmt --check
